# Generated by Django 4.0.5 on 2022-06-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0002_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
