# Generated by Django 4.0.5 on 2022-06-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0003_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='User_image'),
        ),
    ]
